[package]
name = "dm_vibrato"
version = "0.1.0"
edition = "2021"

[dependencies]
lv2 = { version = "0.6.0", features = ["minimal_plugin"] }
vibrato = { path = "../vibrato" }

[lib]
crate-type = ["cdylib"]